debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web.servlet: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.practice.boardpractice: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: cru
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
